export const fr = {
    actions: "Actions",
    addAnswer: "Add an answer",
    addForum: "Create forum",
    addLink: "Add a link",
    addPoll: "Add a poll",
    attachPicture: "Attach a picture",
    author: "Author",
    edit: "Edit",
    editForum: "Edit forum",
    externalLinks: "External links",
    close: "Close",
    closeDate: "Close date",
    comment: "Comment",
    commentsLowerCase: "comments",
    openDate: "Open date",
    possibleAnswers: "Possible answers",
    pinned: "Pinned",
    save: "Save",
    savePoll: "Save poll",
    send: "Send",
    newThread: "New thread",
    read: "Read",
    question: "Question",
    text: "Text",
    title: "Tile",
    vote: "Vote",
    write: "Write",
    writeNews: "Write news",
    writtenOn: "Written on "
}