export const fr = {
    actions: "Actions",
    addAnswer: "Ajouter une réponse",
    addForum: "Ajouter le forum",
    addLink: "Ajouter un lien",
    addPoll: "Ajouter un sondage",
    attachPicture: "Joindre une image",
    author: "Auteur",
    edit: "Éditer",
    editForum: "Modifier le forum",
    externalLinks: "Liens externes",
    close: "Fermer",
    closeDate: "Date de fermeture",
    comment: "Commenter",
    commentsLowerCase: "commentaires",
    openDate: "Date d'ouverture",
    possibleAnswers: "Réponses possibles",
    pinned: "Épinglé",
    save: "Enregistrer",
    savePoll: "Enregistrer le sondage",
    send: "Envoyer",
    newThread: "Nouvelle discussion",
    read: "Lecture",
    question: "Question",
    text: "Texte",
    title: "Titre",
    vote: "Voter",
    write: "Écriture",
    writeNews: "Rédiger une brève",
    writtenOn: "Rédigé le "
}